### ISSUE TITLE
IO functions that return null are not visible to the user

### ISSUE THREAD

**Issue by lucaskniight** [interval/interval-node#1]
Hi, first of all, amazing software.

I've noticed that if I run io.display.markdown at the end of an action, I can't see it and instead I'm shown the success page.

This is likely due to the fact that there's nothing else that the programs waiting for, just possibly worth a mention on the docs that if you're going to display markdown content at the end of a function you should probably follow that with a "End action" confirm or something similar ;)

**Comment by jacobmischka** [comment]
Thanks for the issue and for checking out the product!

Did you `await` the `io.display.markdown` call? It should pause execution there and wait for the response before actually finishing if so. But yes, if you don't `await` the asynchronous call then your function will continue execution and probably return soon after.

If you want to display some information at the end and not wait you can return it from the function and it will be displayed.

```ts
    hello_world: async io => {
      await io.display.markdown('Hello, world!')
    },
    hello_world_return: async () => {
      return 'Hello, world!'
    },
```

https://user-images.githubusercontent.com/3939997/173029660-4381295a-f4f4-4191-aaf8-13fe0d4522a7.mp4

Thanks again!

**Comment by jacobmischka** [comment]
Just following up, does that answer your question? Are you still seeing issues?
