### ISSUE TITLE
Two search boxes in a group lead to "BAD_RESPONSE" errors

### ISSUE THREAD

**Issue by alex-mandriko** [interval/interval-node#14]
Steps to reproduce:
1. Create an action with an `io.group` containing two `io.search` components
2. As you input terms into one of the search components, pause to timeout and get "No results", then proceed to input a term that would return a result
3. Click continue
Expected result: No errors
Result with 0.32.0: The code throws "BAD_RESPONSE" error.

This does not happen with only one search input on the screen.

I've got a recording and a code example to demo the issue that I'm not comfortable sharing publicly. Please contact me if you have trouble duplicating

**Comment by alexarena** [comment]
Hey @alex-mandriko, thank you for reporting this! We were able to identify the problem and a new version of the SDK with a fix will be shipped today. I'll update this thread once that happens.

**Comment by jacobmischka** [comment]
Thank you for raising this issue! This should be fixed now with [v0.33.0](https://interval.com/changelog/0-33-0).
