### ISSUE TITLE
Ability to specify where "New Transaction" button redirects to

### ISSUE THREAD

**Issue by albertorestifo** [interval/interval-node#18]
Sometimes it's useful to build actions that link to multiple unlisted actions.

Example:

- One action to list records in a table, allowing users to select a record
- It links to an unlisted action showing the details of such record
- This record details page links to different hidden actions, each to perform different complex actions on that record
- As a last step, if the user click on "New Transaction" we want to redirect to the list of records, and not to the page listing the details of the record.

**Comment by danphilibin** [comment]
@albertorestifo Hi, thanks for opening this issue! 

One important distinction is that the 'New Transaction' button is only visible in Development mode, so I'd advise against using that button for anything other than restarting the current action while developing it. This is not clear in the UI or in the docs so I apologize for that, and we've made a note to improve this in the future.

Two other features you might find helpful:

- [Pages](https://interval.com/docs/concepts/pages) are a relatively new feature that are designed specifically for listing records in a table and linking to unlisted actions. You can definitely still use Actions for this, Pages just give you nicer navigation.
-  You can use [ctx.redirect](https://interval.com/docs/action-context/redirect) to redirect to other pages at any time during the action. I've personally used this a few times to skip the 'Completed' screen after creating/updating/deleting records and instead take the user back to the list of records. If I understand correctly I think this would solve your last bullet point, and wouldn't even require an extra button click.

**Comment by albertorestifo** [comment]
Excellent tips, those definetely fit the use-case!
