### ISSUE TITLE
No pong received in the last three minutes

### ISSUE THREAD

**Issue by albertorestifo** [interval/interval-node#21]
In our staging environment we're getting a ton of logs from Interval:

```
[Interval]  No pong received in last three minutes, closing connection to Interval and retrying...
[Interval]  Pong not received in time
[Interval]  NotConnectedError:
at ISocket.ping (/usr/src/node_modules/@interval/sdk/dist/classes/ISocket.js:304:19)
at Timeout._onTimeout (/usr/src/node_modules/@interval/sdk/dist/classes/IntervalClient.js:500:22)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
```

The weird part is that it seems that our Staging environment interval dashboard works as expected.

What's the reason for these logs? And can we turn them off if they're not something critical? They are causing a ton of noise in our log ingestion pipeline.

**Comment by alexarena** [comment]
Hey Alberto, thanks for reporting. We've seen this reported by some other users before, interestingly also in non-production environments. We're investigating + trying to reproduce, but like you said - it doesn't seem to have any functional impact.

Worst case scenario, we'll ship an updated SDK with the ability to silence these.  I'll let you know more as we know more!

**Comment by jacobmischka** [comment]
You should be able to set `logLevel: "quiet"` in [v0.36.0](https://interval.com/changelog/0-36-0) to silence these warnings. Thanks for submitting the issue! Let us know if you continue to see any superfluous logs and we'll reinvestigate.
