### ISSUE TITLE
Bug with ctx.loading.start()

### ISSUE THREAD

**Issue by armandoeramos** [interval/interval-node#24]
I was finally able to fix a major bug in my Interval action. The problem was occurring after uploading and processing a CSV file. The processing-file code checks each record against the database and this was happening very quickly in prod. This caused the Interval `ctx.loading` component in my code to freeze after `ctx.loading.completeOne()` (side note: `completeOne() was put at the beginning of the of the body of the `for loop` because said `for loop` as a lot of `continue`s `). The interesting thing is this wasn't happening in my dev environment which made it a hard to find the cause of this bug. After a lot of trial-and-error, I was able to reproduce the bug in dev by commenting-out a lot the database-checking code in my `processData()` method of my Interval action. What this did was speed up `processData()` to a fraction of a second which caused the `ctx.loading` to freeze. What fixed this problem was adding a few `ctx.logs` before `ctx.loading.start()`.

**Comment by jacobmischka** [comment]
Sorry about the issue! Is there any more information you have about your action that was causing issues? Could you please let us know what version of the SDK you're using? Are you seeing any logs in your terminal when the issue happens?

By the way, it's best practice to `await` the `ctx.log` methods, are you doing that? This shouldn't be necessary with the `ctx.loading` methods, though is currently important for frequent `ctx.log` calls. This wasn't previously mentioned in our docs, sorry about that, it is now.

**Comment by armandoeramos** [comment]
No worries! 
To answer your questions:
* I using version 0.34.0
* I'm not seeing any logs in my terminal when the issue happens.
* I'm using `await` with `ctx.logs` methods
* I'm also using `await` with `ctx.loading` methods

Here is a code snippet of how `ctx.logs` is being used:
```
...
// Processing data
await ctx.log("About to process JSON")
const { recordsToBeUpdated, recordsWontBeUpdated, recordsToBeUpdatedForDisplay } = await processData(records)
await ctx.log("Finished processing JSON")
await ctx.log(`Records to be updated: ${JSON.stringify(recordsToBeUpdated.length)}`) // this 
await ctx.log(`Records that won't be updated: ${JSON.stringify(recordsWontBeUpdated.length)}`) // and this fixed bug 
...
```

Here's another code snippet of the body of the `processData()` method:
```
processData(records) {
  const recordsToBeUpdated = []
  const recordsToBeUpdatedForDisplay = []
  const recordsWontBeUpdated = []

  if (records.length > 0) {
    await ctx.loading.start({ title: "Processing file...", itemsInQueue: records.length })
    for (const record of records) {
      await ctx.loading.completeOne()
      // removed a lot of code that makes database and api calls
      ...
      }
  }

  return { recordsToBeUpdated, recordsWontBeUpdated, recordsToBeUpdatedForDisplay }
}
```

**Comment by jacobmischka** [comment]
Thanks for the info! We've identified the issue and have a PR in review that should fix it. We'll write back once that's deployed!

**Comment by armandoeramos** [comment]
Wow, that was quick! Let me know if there is anything else I can help you guys with.

**Comment by jacobmischka** [comment]
This should be deployed and fixed now! Thanks for letting us know, of course please write back if you continue to see the issue.

**Comment by armandoeramos** [comment]
Awesome!
