### ISSUE TITLE
How to get rid of `beforeunload` confirmation dialog?

### ISSUE THREAD

**Issue by Janiczek** [interval/interval-node#28]
We're getting a confirmation dialog when closing an action browser tab. It would be nice to be able to specify that this `beforeunload` behaviour shouldn't happen.

![image (2)](https://github.com/interval/interval-node/assets/149425/eaa5b14c-77d2-4d58-9bac-2c69a7bf318b)

**Comment by jacobmischka** [comment]
You can by setting the `warnOnClose` property of the action to `false`. I see this is missing from our docs at the moment, sorry about that. It definitely was there at one point, so I'm not sure what happened. Apologies, thanks for letting us know!

**Comment by Janiczek** [comment]
Thanks, I'll try this out!

**Comment by Janiczek** [comment]
It totally worked. Thank you!
