### ISSUE TITLE
get id from routing path

### ISSUE THREAD

**Issue by well-balanced** [interval/interval-node#29]
Hi, thanks for making great tools :)
I wonder if there is a way to dynamically deliver ID values to the routing path and get them.
are there any solutions?

**Comment by alexarena** [comment]
Hi! I believe what you're looking for is [context params](https://interval.com/docs/action-context/). Inside of an action, you can use them like this:

```ts
import { Action, io, ctx } from "@interval/sdk";


export default new Action({
  name: "User ID lookup tool",
  handler: async () => {
    let userId = ctx.params.userId
    if (!userId) {
      userId = await io.input.text("User ID to lookup")
    }
    // ... rest of your action
  },
});
```

If you went to the URL of your action and added `?userId=abc` as a query param, that would be passed into this action as `ctx.params.userId`.

Assuming this answers your question, I'm going to close the issue, but feel free to reopen if it didn't!
